Completed es6-destructuring.
bookaneers/m1-321-code-solutions pull request #67
Opened 2021-05-12 03:41 UTC by bookaneers

es6-destructuring | Fernando Figueiredo
![Screen Shot 2021-05-11 at 8 36 08 PM](https://user-images.githubusercontent.com/24905313/117914978-2d056200-b299-11eb-8b10-f245ccdcce65.png)

2021-05-12 03:43 UTC, Zhiwutian requested changes
small update!

2021-05-12 03:43 UTC, Zhiwutian commented on es6-destructuring/main.js
> +const [fourth] = library;
small update needed here. This is assigning the same object as `book3` above. Destructuring does not change the original array, so using only one value here is selecting the first item of the array.

2021-05-12 23:17 UTC, bookaneers commented
es6-destructuring | Fernando Figueiredo
![Screen Shot 2021-05-12 at 4 14 38 PM](https://user-images.githubusercontent.com/24905313/118055709-79a27900-b33d-11eb-8575-4ac53ba0b74f.png)

2021-05-13 17:24 UTC, Zhiwutian approved these changes
👍🏼

2021-05-13 19:27 UTC, merged